
hp:
  T: 12
  act_fn: hard_tanh
  batch_size: 128
  beta: 1.0
  beta_factor: 1.0
  beta_ir: 0.0
  epochs: 50
  dataset: TinyImageNet
  model: VGG7
  se_flag: false
  optim:
    w:
      lr: 7.961890843897934e-05
      wd: 3.5299055677719896e-05
    x:
      lr: 0.02233810859424211
      momentum: 0.55

