direction: minimize
gpus_per_task: 1
seed: 0
hp:
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: leaky_relu
    max_seq_len: 10
    train_size: 900
    test_size: 100
    epochs: 5
    T: 8
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 5e-1], null, true]
                default: 0.8
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.0
        w:
            name: sgd
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 0.1
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 0.0
            momentum: 0.0

