
hp:
  T: 7
  act_fn: gelu
  batch_size: 128
  beta: 0.2
  beta_factor: 0
  beta_ir: 0.02
  dataset: TinyImageNet
  epochs: 50
  model: VGG5
  optim:
    w:
      lr: 0.0001144535829079737
      wd: 0.0016055536430741842
    x:
      lr: 0.07670833046926837
      momentum: 0.4
  se_flag: true

