
hp:
  T: 4
  act_fn: gelu
  batch_size: 128
  beta: 0.1
  beta_factor: 1.0
  beta_ir: 0.0
  epochs: 50
  dataset: TinyImageNet
  model: VGG5
  se_flag: true
  optim:
    w:
      lr: 7.254463449342445e-05
      wd: 0.00010237178120121746
    x:
      lr: 0.035892501613178085
      momentum: 0.05

