
hp:
  T: 8
  act_fn: gelu
  batch_size: 128
  beta: 0.5
  beta_factor: -1.0
  beta_ir: 0.0
  epochs: 50
  dataset: TinyImageNet
  model: VGG5
  se_flag: true
  optim:
    w:
      lr: 0.0001376789472968569
      wd: 1.6046037514265988e-05
    x:
      lr: 0.0573599016772709
      momentum: 0.1

