direction: minimize
gpus_per_task: 1
dataset_name: cifar10
num_classes: 10
seed: 0
hp:
    act_fn:
        sample_type: categorical
        sample_space: [relu, leaky_relu, gelu, tanh, hard_tanh]
        default: leaky_relu
    num_layers: 8
    hidden_dim: 128
    skip_error_layer_indices: [2, 5]
    freeze_skip_layers: false
    beta: 1.0
    beta_annealing: true
    batch_size: 200
    epochs: 20
    T: 8
    optim:
        x:
            lr:
                sample_type: float
                sample_space: [[1e-2, 5e-1], null, true]
                default: 0.1
            momentum:
                sample_type: float
                sample_space: [[0.0, 0.95], 0.05]
                default: 0.5
        w:
            name: sgd
            lr:
                sample_type: float
                sample_space: [[3e-5, 1e-3], null, true]
                default: 0.01
            wd:
                sample_type: float
                sample_space: [[1e-5, 1e-2], null, true]
                default: 0.001
            momentum: 0.9

